encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit", views.edit, name="edit"),
    path("random", views.random, name="random"),
    path("wiki/<str:title>", views.show_content, name="show_content"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse
from . import util
from random import randrange
import markdown2



def index(request):
	return render(request, "encyclopedia/index.html", {
		"entries": util.list_entries()
	})

def show_content(request, title):
	text = util.get_entry(title)
	if text is None:
		return render(request, "encyclopedia/errorpage.html")
	
	return render(request, "encyclopedia/content.html", {
		"mkd_text": markdown2.markdown(text),
		"title": title.lower()
	})

def search(request):
	if request.method == "GET":
		entries = util.list_entries()
		query = request.GET['q']
		if query.lower() in [entry.lower() for entry in entries]:
			return HttpResponseRedirect(f"/{query}")
		search_results = [entry for entry in entries if query in entry.lower()]
		return render(request, "encyclopedia/search_results.html", {
			"entries": search_results
		})
	return render(request, "encyclopedia/index.html")

class newPageForm(forms.Form):
	new_text = forms.CharField(
		widget=forms.Textarea(attrs={'rows':15, 'cols': 50, 'placeholder': "Type here the new page content: "}),
		label="Create a new page here!",
		max_length= 1000
	)

def create(request):
	if request.method == 'POST':
		form = newPageForm(request.POST)
		if form.is_valid():
			title, _ = util.title_separator(form.cleaned_data["new_text"])
			util.save_entry(title, form.cleaned_data["new_text"])
			return HttpResponseRedirect(reverse("encyclopedia:index"))
		return render(request, "encyclopedia/create.html", {
			"form": form
		})
	return render(request, "encyclopedia/create.html", {
		"form": newPageForm()
	})

def edit(request):
	if request.method == 'POST':
		form = newPageForm(request.POST)
		if form.is_valid():
			title, _ = util.title_separator(form.cleaned_data["new_text"])
			util.save_entry(title, form.cleaned_data["new_text"])
			return HttpResponseRedirect(f'wiki/{title}')
		return render(request, 'encyclopedia:edit.html', {
			"form": form
		})
	
	editable_text = util.get_entry(request.GET['e'])
	editForm = newPageForm(initial={'new_text': editable_text})
	return render(request, 'encyclopedia/edit.html', {
		"form": editForm
	})

def random(request):
	entries = util.list_entries()
	random_page = entries[randrange(0, len(entries))]
	return HttpResponseRedirect(f"wiki/{random_page.lower()}")

encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{ mkd_text|safe }}

    <form action="{% url 'encyclopedia:edit' %}" method="get">
        <input type="hidden" name="e" value="{{ title }}">
        <button type="submit">Edit Text</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create a new page!</h1>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="submit">Create new page.</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit this page!</h1>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="submit">Save page.</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/errorpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1 style="text-align: center;">ERROR! PAGE NOT FOUND</h1>
    <img style="display: block; margin: auto;" src="https://oespecialista.com.br/wp-content/uploads/2021/10/neymar-jr-jogadores-mais-valiosos-do-mundo-e1634240225943-518x307.jpg">
    <form action="/"><button style="display: block; margin: auto;" type="submit">Return</button></form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}"> {{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="get" action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}"> {{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}